jobs:
  windows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-nuget-${{ hashFiles('src/**/*.csproj', 'src/**/packages.config')
          }}
        path: ~/.nuget/packages
        restore-keys: '${{ runner.os }}-nuget-

          '
    - continue-on-error: true
      name: Fetch submodules
      run: git submodule init && git submodule update
    - continue-on-error: true
      name: Configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.3
      with:
        minimum-size: 8GB
    - continue-on-error: true
      name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - continue-on-error: true
      name: Switch to JDK-11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Display java version
      run: java -version
    - continue-on-error: true
      name: Download android-26 API
      run: '%ANDROID_SDK_ROOT%\cmdline-tools\latest\bin\sdkmanager --install "platforms;android-26"

        '
      shell: cmd
    - continue-on-error: true
      name: Build native dependencies
      run: 'make native

        '
      shell: cmd
    - continue-on-error: true
      name: Build java dependencies
      run: 'make java

        '
      shell: cmd
    - continue-on-error: true
      name: Install NuGet dependencies (net)
      run: make nuget Flavor=Net
    - continue-on-error: true
      name: Build keepass2android (net)
      run: 'make msbuild Flavor=Net

        '
    - continue-on-error: true
      name: Build APK (net)
      run: 'make apk Flavor=Net

        '
    - continue-on-error: true
      name: Archive production artifacts (net)
      uses: actions/upload-artifact@v3
      with:
        name: signed APK ('net' built on ${{ github.job }})
        path: 'src/keepass2android/bin/*/*-Signed.apk

          '
    - continue-on-error: true
      name: Install NuGet dependencies (nonet)
      run: make nuget Flavor=NoNet
    - continue-on-error: true
      name: Build keepass2android (nonet)
      run: 'make msbuild Flavor=NoNet

        '
    - continue-on-error: true
      name: Test Autofill
      run: dotnet test
      working-directory: ./src/Kp2aAutofillParserTest
    - continue-on-error: true
      name: Build APK (nonet)
      run: 'make apk Flavor=NoNet

        '
    - continue-on-error: true
      name: Archive production artifacts (nonet)
      uses: actions/upload-artifact@v3
      with:
        name: signed APK ('nonet' built on ${{ github.job }})
        path: 'src/keepass2android/bin/*/*-Signed.apk

          '
    - continue-on-error: true
      name: Perform "make distclean"
      run: make distclean
name: Build keepass2android app
on:
  repository_dispatch:
    types: trigger-ga___build.yml
